added everything
FennaHD/Pokedex pull request #1
Opened 2020-01-28 00:10 UTC by FennaHD

2020-01-28 18:41 UTC, didi9 commented on app/src/androidTest/java/com/example/pokedex/ExampleInstrumentedTest.kt
> +class ExampleInstrumentedTest {
Did you throw this in?

2020-01-28 18:41 UTC, didi9 commented on app/src/main/AndroidManifest.xml
> +
Remove newline

2020-01-28 18:41 UTC, didi9 commented on app/src/main/java/com/example/pokedex/MainActivity.kt
> +
remove newline

2020-01-28 18:41 UTC, didi9 requested changes
> Reviewed 123 of 124 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fennahd/pokedex/1)* status: 123 of 124 files reviewed, 22 unresolved discussions (waiting on @didi9 and @FennaHD)

___
*[app/build.gradle, line 12 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh6exKBoC-Ql2-Qu8R:-Lzh6exKBoC-Ql2-Qu8S:b-z12oic) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/build.gradle#L12)):*
> ```Gradle
>     defaultConfig {
>         applicationId "com.example.pokedex"
>         minSdkVersion 15
> ```

Our minSdkVersion is 21
___
*[app/src/androidTest/java/com/example/pokedex/ExampleInstrumentedTest.kt, line 17 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh6npNAcTwWFgSkQeA:-Lzh6npNAcTwWFgSkQeB:btn5gjd) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/androidTest/java/com/example/pokedex/ExampleInstrumentedTest.kt#L17)):*
> ```Kotlin
>  */
> @RunWith(AndroidJUnit4::class)
> class ExampleInstrumentedTest {
> ```

Did you throw this in?
___
*[app/src/main/AndroidManifest.xml, line 15 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh6soo3xhebschSc6E:-Lzh6soo3xhebschSc6F:b-fgj26b) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/AndroidManifest.xml#L15)):*
> ```XML
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> ```

remove newline
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 17 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhOT-M0Yb5uWqPrfLS:-LzhOT-NEmWShINPqaDB:b-ry29lv) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L17)):*
> ```Kotlin
>         super.onCreate(savedInstanceState)
>         setContentView(R.layout.individual_poke_view)
>         val name = intent.getStringExtra("name")
> ```

put into companion object
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 21 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhPJyi2mb4dgSbWWUv:-LzhPJyi2mb4dgSbWWUw:b-vzxus7) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L21)):*
> ```Kotlin
>         //action bar for loading previous activity
>         val actionbar = supportActionBar
>         actionbar!!.title = "Back"
> ```

use null check (`actionbar?.title`) instead of double-bang
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 21 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhPRRR2ncwH_dot04k:-LzhPRRR2ncwH_dot04l:b-e2o92) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L21)):*
> ```Kotlin
>         //action bar for loading previous activity
>         val actionbar = supportActionBar
>         actionbar!!.title = "Back"
> ```

Try naming it the name of the Pokemon
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 23 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhQ_HlECASRPmt6wBw:-LzhQ_HlECASRPmt6wBx:b-5elkdt) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L23)):*
> ```Kotlin
>         actionbar!!.title = "Back"
>         actionbar.setDisplayHomeAsUpEnabled(true)
>         actionbar.setDisplayHomeAsUpEnabled(true)
> ```

remove one
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 34 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhR6TPE98KI7tZQhqq:-LzhR6TQ1hwuo9s8uXLC:bg778d) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L34)):*
> ```Kotlin
>                 val imageView = findViewById<ImageView>(R.id.pokemonPicture)
>                 Picasso.get().load(response.body()?.sprites?.front_default).resize(400, 400).into(imageView)
>                 findViewById<TextView>(R.id.name).text = getString(R.string.pokemon_name, response.body()?.name?.capitalize())
> ```

use kotlin synthetics (e.g. `name.text = ...`)
___
*[app/src/main/java/com/example/pokedex/IndividualActivity.kt, line 37 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhRgrE01BZKXTcyR9U:-LzhRgrE01BZKXTcyR9V:bgo2i51) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/IndividualActivity.kt#L37)):*
> ```Kotlin
>                 findViewById<TextView>(R.id.weight).text = getString(R.string.pokemon_weight, response.body()?.weight)
>                 findViewById<TextView>(R.id.height).text = getString(R.string.pokemon_height, response.body()?.height)
>                 val sb = StringBuilder("Type: ")
> ```

try using `.joinToString()`
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 16 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhHl-6EBOzPzW9O6ac:-LzhHl-7E0IuGbAmGjeU:b-y0zyru) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L16)):*
> ```Kotlin
> import retrofit2.Response
> 
> class MainActivity : AppCompatActivity() {
> ```

reformat (let's compare formatting settings)
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 17 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh6wPKApd0KNGhOS0Z:-Lzh6wPKApd0KNGhOS0_:b-fgj26b) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L17)):*
> ```Kotlin
> 
> class MainActivity : AppCompatActivity() {
> ```

remove newline
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 24 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh7JzC7CDYJ6wMJVqd:-Lzh7JzC7CDYJ6wMJVqe:b-i33n9l) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L24)):*
> ```Kotlin
> 
>         var pokemonList: List<PokemonSummary>?
>         val pokedexService = PokeApiService.create()
> ```

You could inline both of these
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 31 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-LzhBPMH6uWlCOOXhes7:-LzhBPMH6uWlCOOXhes8:bkkd11i) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L31)):*
> ```Kotlin
>                 pokemonList = response.body()?.results
>                 pokemonList?.forEach {
>                     constraintLayout.addView(createButton(this@MainActivity, it.name))
> ```

Interesting solution! This is an instance where we would use a RecyclerView. Check out RecyclerViews and see if you can change all of this to use a RecyclerView. Let me know if you have any questions
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 41 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh7dZG-pHTe33ujRVe:-Lzh7dZG-pHTe33ujRVf:bpxhrp4) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L41)):*
> ```Kotlin
> 
>     fun createButton(context: Context, name: String): Button {
>         var button = Button(context)
> ```

use `.apply { ... }`
___
*[app/src/main/java/com/example/pokedex/MainActivity.kt, line 51 at r1](https://reviewable.io/reviews/fennahd/pokedex/1#-Lzh7juaAjsZH2lMarm4:-Lzh7juaAjsZH2lMarm5:b-gpijph) ([raw file](https://github.com/fennahd/pokedex/blob/aa432cf1e99aca37761fe414092493f02911e804/app/src/main/java/com/example/pokedex/MainActivity.kt#L51)):*
> ```Kotlin
>             val intent = Inte [...]

2020-01-28 18:41 UTC, didi9 reviewed
> Reviewed 1 of 124 files at r1.
> *[Reviewable](https://reviewable.io/reviews/fennahd/pokedex/1)* status: all files reviewed, 22 unresolved discussions (waiting on @FennaHD)



<!-- Sent from Reviewable.io -->

2020-01-31 15:47 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/fennahd/pokedex/1)* status: 101 of 125 files reviewed, 26 unresolved discussions (waiting on @didi9, @FennaHD, and @romrell4)

___
*[.idea/.name, line 1 at r2](https://reviewable.io/reviews/fennahd/pokedex/1#-LzwHDfK4etFITM7HdIc:-LzwHDfK4etFITM7HdId:b-lsv9g7) ([raw file](https://github.com/fennahd/pokedex/blob/f53dbb3c9d577fa8fa6f95e319104f5b7e0e066d/.idea/.name#L1)):*
> ```
> Pokedex
> ```

We gitignore the .idea file. Do you know how to use gitignore?


<!-- Sent from Reviewable.io -->

2020-01-31 15:47 UTC, romrell4 requested changes
> *[Reviewable](https://reviewable.io/reviews/fennahd/pokedex/1)* status: 101 of 125 files reviewed, 27 unresolved discussions (waiting on @didi9, @FennaHD, and @romrell4)

___
*[Pokedex.iml, line 1 at r2](https://reviewable.io/reviews/fennahd/pokedex/1#-LzwHJnL6sUqEo_mSjoo:-LzwHJnL6sUqEo_mSjop:bc4dgxv) ([raw file](https://github.com/fennahd/pokedex/blob/f53dbb3c9d577fa8fa6f95e319104f5b7e0e066d/Pokedex.iml#L1)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> ```

We gitignore the *.iml files


<!-- Sent from Reviewable.io -->

2020-02-06 21:05 UTC, closed without merging